apiVersion: v1
kind: ServiceAccount
metadata:
  name: net-sec-watch-collector
  namespace: net-sec-watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: net-sec-watch-opensearch
  namespace: net-sec-watch
